#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /tmp
rsync -a /source .
cd source
make
mv su-exec /usr/bin

cd /out
# this is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# remember to list all your runtime dependencies, e.g. the shared libraries you link to.
fpm -t deb -s dir -n su-exec --version ${VERSION} --description "su-exec ${GIT_COMMIT}" -C / /usr/bin/su-exec
