FROM ubuntu:trusty
# we add the games user to the "users" group; that's not the default in all distros,
# but I'd like to keep the tests identical.
RUN usermod -a -G users games


# add "nobody" to ALL groups (makes testing edge cases more interesting)
RUN cut -d: -f1 /etc/group | xargs -n1 addgroup nobody

RUN { \
		echo '#!/bin/sh'; \
		echo 'set -ex'; \
		echo; \
		echo 'spec="$1"; shift'; \
		echo; \
		echo 'expec="$1"; shift'; \
		echo 'real="$(su-exec "$spec" id -u):$(su-exec "$spec" id -g):$(su-exec "$spec" id -G)"'; \
		echo '[ "$expec" = "$real" ]'; \
		echo; \
		echo 'expec="$1"; shift'; \
		# have to "|| true" this one because of "id: unknown ID 1000" (rightfully) having a nonzero exit code
		echo 'real="$(su-exec "$spec" id -un):$(su-exec "$spec" id -gn):$(su-exec "$spec" id -Gn)" || true'; \
		echo '[ "$expec" = "$real" ]'; \
	} > /usr/local/bin/su-exec-t \
	&& chmod +x /usr/local/bin/su-exec-t

COPY *.deb /tmp
RUN dpkg -i /tmp/*.deb

# adjust users so we can make sure the tests are interesting
RUN chgrp nogroup /usr/bin/su-exec \
	&& chmod +s /usr/bin/su-exec
USER nobody
ENV HOME /omg/really/su-exec/nowhere
# now we should be nobody, ALL groups, and have a bogus useless HOME value


RUN id

RUN su-exec-t 0 "0:0:$(id -G root)" "root:root:$(id -Gn root)"
RUN su-exec-t 0:0 '0:0:0' 'root:root:root'
RUN su-exec-t root "0:0:$(id -G root)" "root:root:$(id -Gn root)"
RUN su-exec-t 0:root '0:0:0' 'root:root:root'
RUN su-exec-t root:0 '0:0:0' 'root:root:root'
RUN su-exec-t root:root '0:0:0' 'root:root:root'
RUN su-exec-t 1000 "1000:$(id -g):$(id -g)" "1000:$(id -gn):$(id -gn)"
RUN su-exec-t 0:1000 '0:1000:1000' 'root:1000:1000'
RUN su-exec-t 1000:1000 '1000:1000:1000' '1000:1000:1000'
RUN su-exec-t root:1000 '0:1000:1000' 'root:1000:1000'
RUN su-exec-t 1000:root '1000:0:0' '1000:root:root'
RUN su-exec-t 1000:daemon "1000:$(id -g daemon):$(id -g daemon)" '1000:daemon:daemon'
RUN su-exec-t games "$(id -u games):$(id -g games):$(id -G games)" 'games:games:games users'
RUN su-exec-t games:daemon "$(id -u games):$(id -g daemon):$(id -g daemon)" 'games:daemon:daemon'

RUN su-exec-t 0: "0:0:$(id -G root)" "root:root:$(id -Gn root)"
RUN su-exec-t '' "$(id -u):$(id -g):$(id -G)" "$(id -un):$(id -gn):$(id -Gn)"
RUN su-exec-t ':0' "$(id -u):0:0" "$(id -un):root:root"

RUN [ "$(su-exec 0 env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec 0:0 env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec root env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec 0:root env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec root:0 env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec root:root env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec 0:1000 env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec root:1000 env | grep '^HOME=')" = 'HOME=/root' ]
RUN [ "$(su-exec 1000 env | grep '^HOME=')" = 'HOME=/' ]
RUN [ "$(su-exec 1000:0 env | grep '^HOME=')" = 'HOME=/' ]
RUN [ "$(su-exec 1000:root env | grep '^HOME=')" = 'HOME=/' ]
RUN [ "$(su-exec games env | grep '^HOME=')" = 'HOME=/usr/games' ]
RUN [ "$(su-exec games:daemon env | grep '^HOME=')" = 'HOME=/usr/games' ]

# something missing?  some other functionality we could test easily?  PR! :D
